
ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'Foundation',
  ADD COLUMN IF NOT EXISTS required_role TEXT NOT NULL DEFAULT 'free',
  ADD COLUMN IF NOT EXISTS emoji TEXT NOT NULL DEFAULT '📘',
  ADD COLUMN IF NOT EXISTS lesson_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duration_minutes INTEGER NOT NULL DEFAULT 0;
